### ISSUE TITLE
minor: automatic TOC structure

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/awesome-modelica#10]
github automatically creates a TOC
https://twitter.com/github/status/1376636651963842562
https://github.com/isaacs/github/issues/215#issuecomment-815630110

This is how the structure looks like currently:
![image](https://user-images.githubusercontent.com/314571/114007145-5f1e4100-9861-11eb-92c4-e4520f3eae34.png)

Might be possible to resturcture to make it easier to navigate.

**Comment by greenwoodms06** [comment]
Finally! Been looking forward to having something like that. I corrected a minor heading setup. I think with that commit the auto-readme looks ok. That auto TOC is a new feature so perhaps they might make it more feature rich in the future. Have any specific suggestion?

**Comment by thorade** [comment]
Maybe the only point is that the TOC has quite many levels and as a result becomes quite long. Maybe try to restrict it to TWO levels only? For example, the subsections for each tool might be overkill, as long as there are only 1-2 links in each section.
