### ISSUE TITLE
Linkedin

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/awesome-modelica#2]
Linkedin has a Modelica group
https://www.linkedin.com/groups/806917/

Imke Krüger has posted a list of resources on Linkedin:
https://www.linkedin.com/posts/imke-kr%C3%BCger-a8044375_join-the-modelica-discord-server-activity-6715156022773854209-Brzh

**Comment by thorade** [comment]
https://www.linkedin.com/groups/4400628/
https://www.linkedin.com/groups/12431484/

**Comment by greenwoodms06** [comment]
added include some (but not all) of the items from the linkedin post
