### ISSUE TITLE
awesome-list

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/awesome-modelica#5]
Just an idea, maybe you want to make align your list with the many awesome-lists out there
https://github.com/traversaro/awesome-fmi
https://github.com/sindresorhus/awesome
It seems awesome-modelica is not yet taken...

**Comment by greenwoodms06** [comment]
hmmmmm.... not a bad idea...

**Comment by greenwoodms06** [comment]
alrighty. i am going to rename this repo now
