### ISSUE TITLE
openmodelica spoken tutorials

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/awesome-modelica#8]
Some good introductory material is listed here:
https://openmodelica.org/useresresources/modelica-courses

These courses use OpenModelica, but it really could be any tool. Your decision which section to add it to.

There is one easy to miss link on that page:
https://spoken-tutorial.org/tutorial-search/?search_foss=OpenModelica&search_language=English

**Comment by greenwoodms06** [comment]
added
