### ISSUE TITLE
Dymola on stackoverflow

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/awesome-modelica#9]
I think this is not yet in the list:
https://stackoverflow.com/questions/tagged/dymola
On the other hand, this is in the list:
https://stackoverflow.com/questions/tagged/modelica

**Comment by thorade** [comment]
More tool-specific tags:
https://stackoverflow.com/questions/tagged/systemmodeler
https://stackoverflow.com/questions/tagged/simulationx

**Comment by greenwoodms06** [comment]
I leaned towards just the modelica tag as typically all other tags also include the Modelica tag. Seemed this was a better choice than listing all the potential tags.

**Comment by greenwoodms06** [comment]
went ahead and added dymola and systemmodeler.
